version: "3.8"

services:
  
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    network_mode: "host"  # Needed for DNS on all interfaces
    expose: # used for documentation; ignored in host mode
      - "53/tcp"
      - "53/udp"
      - "80/tcp"
    environment:
      TZ: "YOUR_TIMEZONE"
      WEBPASSWORD: "yourpassword"
      DNS1: 1.1.1.1
      DNS2: 8.8.8.8
    volumes:
      - ./pihole_data/etc-pihole:/etc/pihole
      - ./pihole_data/etc-dnsmasq.d:/etc/dnsmasq.d
      - ./pihole_data/custom-dns:/etc/dnsmasq.d/custom
    restart: unless-stopped
